# Concatenate engine + botzone entry into a single file for Botzone submission.
# Usage: powershell -ExecutionPolicy Bypass -File tools\make_botzone.ps1
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

$files = @(
    "$root\engine\chess.h",
    "$root\engine\chess.cpp",
    "$root\engine\search.h",
    "$root\engine\search.cpp",
    "$root\botzone\botzone_main.cpp"
)

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine('// ============================================================')
[void]$out.AppendLine('// Chinese Chess bot, Botzone single-file build (auto-generated)')
[void]$out.AppendLine('// by tools/make_botzone.ps1. DO NOT edit this file by hand;')
[void]$out.AppendLine('// sources live in engine/ and botzone/ directories.')
[void]$out.AppendLine('// ============================================================')
foreach ($f in $files) {
    foreach ($line in (Get-Content -LiteralPath $f -Encoding UTF8)) {
        # Drop includes of project-own headers (already inlined by concatenation)
        if ($line -match '^\s*#\s*include\s+"(chess|search)\.h"') { continue }
        [void]$out.AppendLine($line)
    }
}

$dest = "$root\botzone\botzone_submit.cpp"
Set-Content -LiteralPath $dest -Value $out.ToString() -Encoding UTF8
Write-Output "generated: $dest"
